name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # Fail the build only on critical Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Allow higher complexity, longer line length, and ignore minor stylistic warnings
          flake8 . --count --max-complexity=20 --max-line-length=150 --ignore=E127,E266,E303,E305,E502,W292,W504 --statistics

      - name: Run Local Tests with pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -v test_ml.py

      - name: Wait for Render Deployment
        # Assuming the Render service provides a specific URL once it's up.
        run: |
          echo "Waiting for Render service to be up... Waiting 300 seconds"
          sleep 300
          echo "Render service should be up now!"

      - name: Run Remote Tests with pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -v test_main.py